name: CI — Build & Verify (unit tests)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      FAIL_ON_LINT: \"false\"   # TEMP: allow lint warnings while we fix them

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18' # From package.json engines field

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Type check (TEMP: non-fatal)
        run: npx tsc --noEmit || true

      - name: Build
        run: npm run build

      - name: Lint (fail on warnings if FAIL_ON_LINT=true)
        run: |
          if [ "${{ env.FAIL_ON_LINT }}" = "true" ]; then
            npm run lint -- --max-warnings=0
          else
            npm run lint || true
          fi

      - name: Run tests (placeholder - tests not configured yet)
        run: echo "Tests not yet configured - skipping for now"

      - name: Archive build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            automation-logs/
            logs/
            .next/
            build/logs/
            *.log
